### PR TITLE
Add syntax-error as a code

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by adrienverge** [comment]
Hey @sylvestre, why not, I'm curious about the use-case? And can you change `syntax-error` to `syntax`?

**Comment by sylvestre** [comment]
Good question, I should have been more explicit! ;)

We are using your tool for Firefox YAML linting (merci btw)
We parse the results with this regexp
`YAMLLINT_FORMAT_REGEX = re.compile(r'(.*):(.*):(.*): \[(error|warning)\] (.*) \((.*)\)$')`
https://searchfox.org/mozilla-central/source/tools/lint/yamllint_/__init__.py#26

which expects the error code. Which doesn't exit with the syntax-error...
We could work around that in our code but I think it should be done upstream instead.

**Comment by adrienverge** [comment]
De rien :) I'm glad to know that Mozilla uses yamllint.

Thanks for your contribution!

**Comment by sylvestre** [comment]
@adrienverge any chance you could publish a release with this change?
thanks

**Comment by adrienverge** [comment]
Sure, let's create the last release of 2019! :christmas_tree: 
https://github.com/adrienverge/yamllint/releases/tag/v1.20.0

**Pull request merged**
