### PR TITLE
Added dockerfile

### PR DESCRIPTION
**Pull request by xtellurian**
* This PR adds a dockerfile

* The image let's you run yamllint with the command:

```
docker run -v `pwd`:/files IMAGE:TAG /files
```

### CODE REVIEW

**Comment by adrienverge** [comment]
Thanks for your contribution, however since yamllint is a tool, not a service, I don't see the need to have an official Docker image nor a Dockerfile in the repo. Moreover it's preferable not to start maintaining packaging scripts (.spec, control, Dockerfile...) here.

**Comment by neluzhin** [comment]
@adamchainz, [gcloud](https://hub.docker.com/r/google/cloud-sdk/) (CLI client for Google Cloud) and [sentry-cli](https://hub.docker.com/r/getsentry/sentry-cli) (CLI client for Sentry) are tools too, but they provide official Docker images for their CLI applications and we found them useful in our CI pipelines.

The main difference between yamllint and, for example, [ESLint](https://eslint.org/) is simple: ESLint relates to JavaScript ecosystem, it's served via NPM and every JS developer know how to deal with it. yamllint doesn't stick to any ecosystem, it's just "tool for linting YAML files", and there are a lot of people who don't know what to do with Python, pip and other things to make it work. I am unfamiliar with Python and it's ecosystem and I asked my friend to set up Docker image for my CI. Be sure: I am not the only one developer who faced the same problem.

That's my opinion why yamllint needs official Docker image and why it should be served via popular package managers such as APT, APK, Snap and others.

**Comment by adamchainz** [comment]
Don't @ me on threads that I've not participated on just because I'm first on your autocomplete.

Anyway since you brought me in, my 2 cents are that Python package maintainers shouldn't be expected to repackage things on Docker (or debs, or rpms, or...) too. @adrienverge has limited time and I'd prefer he just spent it on making `yamllint` better (and he does a great job there!)

**Comment by adrienverge** [comment]
Thanks for your inputs guys.

I agree with you @adamchainz, packaging (for APT, APK, Brew... or Docker) is cumbersome and I prefer not to maintain this in this repo.

@neluzhin I understand your point, but you're assuming that "*pip is not universal/standard*", while "*Docker is*". I disagree.
I think the responsibility of packaging this tool for a given environment (a Linux distro, Docker, Brew...) should be distributed. For your information, I package yamllint for Fedora and CentOS, but don't commit `.spec` files here.
If you want to create an "official" Docker image, I encourage you! 🙂

**Comment by xtellurian** [comment]
@neluzhin you can access a dockerized version of yaml lint via [my fork of yamllint](https://github.com/xtellurian/yamllint) and is available in [Docker Cloud](https://cloud.docker.com/u/xtellurian/repository/docker/xtellurian/yamllint)

@adrienverge IMO the Docker image should be relatively easy to maintain.  You just have to configure a Docker Cloud build to point to this repository, and all changes here will be automatically built + released. Otherwise feel free to point interested parties to [this Docker image](https://cloud.docker.com/u/xtellurian/repository/docker/xtellurian/yamllint)

**Comment by adrienverge** [comment]
> IMO the Docker image should be relatively easy to maintain

No doubt about that (I maintain other Docker images).
Taken alone, maintaining the Dockerfile is relatively easy. Taken alone, maintaining an APT package is easy. Taken alone, maintaining a RPM package is easy. Same for an APK package, taken alone. And for a Homebrew package. Etc...

**Comment by arbourd** [comment]
> Thanks for your contribution, however **since yamllint is a tool, not a service**, I don't see the need to have an official Docker image nor a Dockerfile in the repo.

Modern CI platforms generally rely on Docker images as their source. For example, I use `yamllint` on my repos with CircleCI to ensure my yaml is sane.

It's an extremely common pattern to find Dockerfiles in the source repo, be it a tool, service, etc.

> I understand your point, but you're assuming that "pip is not universal/standard", while "Docker is". I disagree.

It's not even about `pip`, it's about the entire Python run-time. You do not need to have it installed because of Docker. It can run on Windows, *nix, BSD, etc.

I understand you don't want to maintain it and I can understand why. For those of us who maintain CI platforms (especially for large companies who want verifiable builds) having the source Dockerfile exist and be built by the source itself is extremely important. Compared to `randomperson/yamllint`, your repo is less likely to be compromised, likely to be up to date, etc.

**Comment by adamchainz** [comment]
> For those of us who maintain CI platforms (especially for large companies who want verifiable builds) having the source Dockerfile exist and be built by the source itself is extremely important.

You say you're working for a a large company, or at least maintaining a CI platform. Adrien is a volunteer making an open source tool.

If Adrien declares something as out of scope for the project, don't push on old threads trying to bully him into doing it.

Make and maintain the docker image yourselves if it's *extremely important* to your business. There's a Dockerfile to begin with right on this PR.

Adrien might even link to your image as "unofficial" if you're nice!

**Comment by arbourd** [comment]
I'm not pushing on old threads, see: https://github.com/adrienverge/yamllint/pull/191#issuecomment-511314933

Please understand that me expressing my opinion on the importance of this feature after submitting a PR for it is not bullying. I am not demanding, complaining or demonizing Adrien's opinion. I am simply pointing out the advantages for us who consume it, and acknowledged his reasons for being hesitant.

I understand how open source works. I understand that I work for a company. Frankly, I can't help but read your response as patronizing. That's disappointing.

**Comment by adrienverge** [comment]
I agree with Adam that neither #191 nor these last posts add anything new (except that it's *extremely* important).

Again, I'm not against an "official" Docker image, I just don't want to maintain it (for time and security/responsibility reasons). I already maintain Docker images, I already maintain yamllint Pip and RPM packages and that's enough for me.

I encouraged people to create an official Docker image, but nothing came out of this. We can also think of a dedicated branch (`packaging/docker`) here (adrienverge/yamllint) that you could maintain? It needs to be updated every time there is a new version, probably for years. It needs to be taken care of seriously, otherwise people will complain here.  Do you (or anyone) volunteer?

**Comment by adamchainz** [comment]
> Please understand that me expressing my opinion on the importance of this feature after submitting a PR for it is not bullying.

I apologize for my overly harsh labelling here, and did not mean to patronize. I'm not a maintainer of yamllint, so please don't take my comments as a representation of the project.

**Comment by neluzhin** [comment]
> It needs to be updated every time there is a new version, probably for years

Just use CI and some tools for automation such as Renovatebot. There is nothing difficult in writing CI configuration for everything cuz you do it one time (however Docker does not require CI — Docker Hub builds your Dockerfile automatically each time you push to git repository).

**Comment by arbourd** [comment]
> We can also think of a dedicated branch (packaging/docker) here (adrienverge/yamllint) that you could maintain

I think the only way this would work well is with it in master

>It needs to be updated every time there is a new version, probably for years

As @neluzhin said, Docker Hub gives you this for free. You can have it build on tags (which you are already using) which can build and label the Docker image each time. 

Here is an example: https://hub.docker.com/r/arbourd/concourse-slack-alert-resource/tags

- When a change to master is made, it builds an image with tag `master`
- When a tag is created, it builds two images; one tagged `latest` (which is always mutable, the latest tag) and `vX.X.X`.

This happens with zero intervention from me. 

Of course, if Docker Hub fails for some reason or there's a bug with the Dockerfile, there's an error. I'd have no problem helping maintain this, but, I would need some level of ownership over the repository (Dockerfile).

I also don't want to stress you. We can survive with other images too. I completely understand not wanting to take on something that I (or others) might bail on 😬

**Pull request closed without merging**
