### PR TITLE
Add the ability to run custom rules included in a project

### PR DESCRIPTION
**Pull request by pdericson**
This is a little rough but I figured I'd raise it now to gauge interest.

### CODE REVIEW

**Comment by adrienverge** [comment]
Hey @pdericson,

Nice work!

Although the idea of "pluggable rules" looks good, I don't like yamllint automatically loading rules from the current dir. This would allow untrusted sources (example: a pull request on GitHub) to run arbitrary Python code. Maybe a `--plugin` option would be better? And it would allow pluggable rules installed system-wide.

Could you give more details about your use-case? Is the "truthy" rule just an example, or something you really want to lint?

**Comment by pdericson** [comment]
Hey @adrienverge, I'll rework my PR to make this explicitly opt-in like you suggest.  Regarding the "truthy" example - I have been thinking about creating an ansible linter for a while and so this example would be something I'd like to include.

**Comment by adrienverge** [comment]
Hi @pdericson,

I can see the use of such a rule!

I guess the motivation is to prevent pyyaml from altering YAML source. Because by default, it turns

```yaml
1: y
2: yes
3: on
4: true
5: True
```
into
```json
{
    "1": "y", 
    "2": true, 
    "3": true, 
    "4": true, 
    "5": true
}
```
and
```yaml
y:    1
yes:  2
on:   3
true: 4
True: 5
```
into
```json
{
    "y": 1, 
    "true": 5
}
```

To be honest I don't really like the pluggable rules idea, but I would warmly welcome a `quote-truthy` rule contribution!

**Comment by pdericson** [comment]
@adrienverge I agree, so far the only yaml linting idea I have had for ansible is the truthy rule which as you have pointed out can be made generic.

I'm going to replace this PR with #22

**Pull request closed without merging**
