### PR TITLE
88 anchor references seen as duplicate key

### LINKED ISSUE #88: anchor references seen as duplicate key
I'm not sure if this is a feature or a bug! :-)

When running yamllint on a yaml file with multiple anchors referenced, you get a duplicate key error. 

EG:

Given the following file:
```yaml
---
anchor_one: &anchor_one
  sequence_one:
    - sequence_one
    - sequence_two

anchor_two: &anchor_two
  sequence_two:
    - sequence_three
    - sequence_four

main:
  <<: *anchor_one
  <<: *anchor_two
  unicorn_settings:
    - non-sequence-sequence
```

Upon running yamllint you get the following error:
```bash
test.yml
  14:3      error    duplication of key "<<" in mapping  (key-duplicates)
```

Python thinks it's "valid" and has the desired data structure:

```python
>>> import yaml, pprint
>>> pp = pprint.PrettyPrinter(indent=2)
>>> file = open("test.yml", "r")
>>> yaml_dump = yaml.load(file)
>>> pp.pprint(yaml_dump)
{ 'anchor_one': { 'sequence_one': ['sequence_one', 'sequence_two']},
  'anchor_two': { 'sequence_two': ['sequence_three', 'sequence_four']},
  'main': { 'sequence_one': ['sequence_one', 'sequence_two'],
            'sequence_two': ['sequence_three', 'sequence_four'],
            'unicorn_settings': ['non-sequence-sequence']}}
```

[As near as I can tell, it seems to be supported by the YAML spec:](http://www.yaml.org/spec/1.2/spec.html#id2765878):

*When composing a representation graph from serialized events, an alias node refers to the most recent node in the serialization having the specified anchor. Therefore, anchors need not be unique within a serialization.*

### PR DESCRIPTION
**Pull request by neekz0r**
fixes #88 

LMK if you spot anything fishy. I couldn't dedicate much time to tracing back so my method may be wrong --- but all unit tests pass so if there is something wrong, it's not covered.

### CODE REVIEW

**Comment by adrienverge** [comment]
Hi @neekz0r, thanks a lot!

Do you think it would be possible to handle this case?

```yaml
duplicate keys:
  <<: {same key: value 1}
  <<: {same key: value 2}
```

**Comment by keymon** [comment]
I would merge this PR directly. For the case described in  https://github.com/adrienverge/yamllint/pull/90#issuecomment-350237615, 

I think we should open a new issue and solve it in other PR. Currently we do not support this case anyway:

```
duplicate keys:
  <<: {same key: value 1}
  same key: value 2
```

**Comment by neekz0r** [comment]
FYI, I'm still "here", but my time is limited to work on the expanded request (low priority for us at JLR, marked as a "nice to have").

So I would tend to agree with @keymon for selfish reasons.

**Comment by adrienverge** [comment]
@keymon @neekz0r you're right.

I've just rebased on `master` and adapted the commits a bit.

Thanks for your contribution!

**Pull request merged**
