### PR TITLE
Changes to simplify setup.py and make packaging stuff easier to maintain

### PR DESCRIPTION
**Pull request by ssato**
Changes to simplify setup.py by moving its some packaging configurations into setup.cfg and add some meta data into setup.cfg.

### CODE REVIEW

**Comment by ssato** [comment]
Just for the record.

I confirmed that making wheel package looks worked and the built package can be installed locally after thse changes were applied.

```
ssato@x1-carbon-gen6% pwd
/home/ssato/repos/public/github.com/ssato/yamllint.git
ssato@x1-carbon-gen6% rm -rf dist build *.egg*
ssato@x1-carbon-gen6% ls
CHANGELOG.rst  CONTRIBUTING.rst  LICENSE  MANIFEST.in  README.rst
docs  setup.cfg  setup.py  tests  yamllint
ssato@x1-carbon-gen6% python3 setup.py bdist_wheel
running bdist_wheel
running build
running build_py
creating build
creating build/lib
        ...
removing build/bdist.linux-x86_64/wheel
ssato@x1-carbon-gen6% ls dist
yamllint-1.24.2-py2.py3-none-any.whl
ssato@x1-carbon-gen6% pip install dist/yamllint-1.24.2-py2.py3-none-any.whl --root /tmp/i --ignore-installed
Processing ./dist/yamllint-1.24.2-py2.py3-none-any.whl
Processing /home/ssato/.cache/pip/wheels/a7/c1/ea/cf5bd31012e735dc1dfea3131a2d5eae7978b251083d6247bd/PyYAML-5.3.1-cp38-cp38-linux_x86_64.whl
Collecting pathspec>=0.5.3
  Using cached https://files.pythonhosted.org/packages/5d/d0/887c58853bd4b6ffc7aa9cdba4fc57d7b979b45888a6bd47e4568e1cf868/pathspec-0.8.0-py2.py3-none-any.whl
Installing collected packages: pyyaml, pathspec, yamllint
  WARNING: The script yamllint is installed in '/tmp/i/usr/local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pathspec-0.8.0 pyyaml-5.3.1 yamllint-1.24.2
ssato@x1-carbon-gen6% find /tmp/i -type f
/tmp/i/usr/local/bin/yamllint
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/conf/default.yaml
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/conf/relaxed.yaml
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/__pycache__/__init__.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/__pycache__/braces.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/__pycache__/brackets.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/__pycache__/colons.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/__pycache__/commas.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/__pycache__/comments.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/__pycache__/comments_indentation.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/__pycache__/common.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/__pycache__/document_end.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/__pycache__/document_start.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/__pycache__/empty_lines.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/__pycache__/empty_values.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/__pycache__/hyphens.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/__pycache__/indentation.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/__pycache__/key_duplicates.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/__pycache__/key_ordering.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/__pycache__/line_length.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/__pycache__/new_line_at_end_of_file.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/__pycache__/new_lines.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/__pycache__/octal_values.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/__pycache__/quoted_strings.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/__pycache__/trailing_spaces.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/__pycache__/truthy.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/__init__.py
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/braces.py
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/brackets.py
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/colons.py
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/commas.py
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/comments.py
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/comments_indentation.py
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/common.py
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/document_end.py
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/document_start.py
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/empty_lines.py
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/empty_values.py
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/hyphens.py
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/indentation.py
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/key_duplicates.py
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/key_ordering.py
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/line_length.py
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/new_line_at_end_of_file.py
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/new_lines.py
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/octal_values.py
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/quoted_strings.py
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/trailing_spaces.py
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/rules/truthy.py
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/__pycache__/__init__.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/__pycache__/__main__.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/__pycache__/cli.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/__pycache__/config.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/__pycache__/linter.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/__pycache__/parser.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/__init__.py
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/__main__.py
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/cli.py
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/config.py
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/linter.py
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint/parser.py
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint-1.24.2.dist-info/RECORD
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint-1.24.2.dist-info/INSTALLER
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint-1.24.2.dist-info/LICENSE
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint-1.24.2.dist-info/METADATA
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint-1.24.2.dist-info/WHEEL
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint-1.24.2.dist-info/entry_points.txt
/tmp/i/usr/local/lib/python3.8/site-packages/yamllint-1.24.2.dist-info/top_level.txt
/tmp/i/usr/local/lib/python3.8/site-packages/pathspec/patterns/__pycache__/__init__.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/pathspec/patterns/__pycache__/gitwildmatch.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/pathspec/patterns/__init__.py
/tmp/i/usr/local/lib/python3.8/site-packages/pathspec/patterns/gitwildmatch.py
/tmp/i/usr/local/lib/python3.8/site-packages/pathspec/tests/__pycache__/__init__.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/pathspec/tests/__pycache__/test_gitwildmatch.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/pathspec/tests/__pycache__/test_pathspec.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/pathspec/tests/__pycache__/test_util.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/pathspec/tests/__init__.py
/tmp/i/usr/local/lib/python3.8/site-packages/pathspec/tests/test_gitwildmatch.py
/tmp/i/usr/local/lib/python3.8/site-packages/pathspec/tests/test_pathspec.py
/tmp/i/usr/local/lib/python3.8/site-packages/pathspec/tests/test_util.py
/tmp/i/usr/local/lib/python3.8/site-packages/pathspec/__pycache__/__init__.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/pathspec/__pycache__/compat.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/pathspec/__pycache__/pathspec.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/pathspec/__pycache__/pattern.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/pathspec/__pycache__/util.cpython-38.pyc
/tmp/i/usr/local/lib/python3.8/site-packages/pathspec/__init__.py
/tmp/i/usr/local/lib/python3.8/site-packages/pathspec/compat.py
/tmp/i/usr/local/lib/python3.8/site-packages/pathspec/pathspec.py
/tmp/i/usr/local/lib/python3.8/site-packages/pathspec/pattern.py
/tmp/i/usr/local/lib/python3.8/site-packages/pathspec/util.py
/tmp/i/usr/local/lib/python3.8/site-packages/pathspec-0.8.0.dist-info/RECORD
/tmp/i/usr/local/lib/python3.8/site-packages/pathspec-0.8.0.dist-info/INSTALLER
/tmp/i/usr/local/lib/python3.8/site-packages/pathspec-0.8.0.dist-info/LICENSE
/tmp/i/usr/local/lib/python3.8/site-packages/pathspec-0.8.0.dist-info/METADATA
/tmp/i/usr/local/lib/python3.8/site-packages/pathspec-0.8.0.dist-info/WHEEL
/tmp/i/usr/local/lib/python3.8/site-packages/pathspec-0.8.0.dist-info/top_level.txt
/tmp/i/usr/local/lib64/python3.8/site-packages/yaml/__pycache__/__init__.cpython-38.pyc
/tmp/i/usr/local/lib64/python3.8/site-packages/yaml/__pycache__/composer.cpython-38.pyc
/tmp/i/usr/local/lib64/python3.8/site-packages/yaml/__pycache__/constructor.cpython-38.pyc
/tmp/i/usr/local/lib64/python3.8/site-packages/yaml/__pycache__/cyaml.cpython-38.pyc
/tmp/i/usr/local/lib64/python3.8/site-packages/yaml/__pycache__/dumper.cpython-38.pyc
/tmp/i/usr/local/lib64/python3.8/site-packages/yaml/__pycache__/emitter.cpython-38.pyc
/tmp/i/usr/local/lib64/python3.8/site-packages/yaml/__pycache__/error.cpython-38.pyc
/tmp/i/usr/local/lib64/python3.8/site-packages/yaml/__pycache__/events.cpython-38.pyc
/tmp/i/usr/local/lib64/python3.8/site-packages/yaml/__pycache__/loader.cpython-38.pyc
/tmp/i/usr/local/lib64/python3.8/site-packages/yaml/__pycache__/nodes.cpython-38.pyc
/tmp/i/usr/local/lib64/python3.8/site-packages/yaml/__pycache__/parser.cpython-38.pyc
/tmp/i/usr/local/lib64/python3.8/site-packages/yaml/__pycache__/reader.cpython-38.pyc
/tmp/i/usr/local/lib64/python3.8/site-packages/yaml/__pycache__/representer.cpython-38.pyc
/tmp/i/usr/local/lib64/python3.8/site-packages/yaml/__pycache__/resolver.cpython-38.pyc
/tmp/i/usr/local/lib64/python3.8/site-packages/yaml/__pycache__/scanner.cpython-38.pyc
/tmp/i/usr/local/lib64/python3.8/site-packages/yaml/__pycache__/serializer.cpython-38.pyc
/tmp/i/usr/local/lib64/python3.8/site-packages/yaml/__pycache__/tokens.cpython-38.pyc
/tmp/i/usr/local/lib64/python3.8/site-packages/yaml/__init__.py
/tmp/i/usr/local/lib64/python3.8/site-packages/yaml/composer.py
/tmp/i/usr/local/lib64/python3.8/site-packages/yaml/constructor.py
/tmp/i/usr/local/lib64/python3.8/site-packages/yaml/cyaml.py
/tmp/i/usr/local/lib64/python3.8/site-packages/yaml/dumper.py
/tmp/i/usr/local/lib64/python3.8/site-packages/yaml/emitter.py
/tmp/i/usr/local/lib64/python3.8/site-packages/yaml/error.py
/tmp/i/usr/local/lib64/python3.8/site-packages/yaml/events.py
/tmp/i/usr/local/lib64/python3.8/site-packages/yaml/loader.py
/tmp/i/usr/local/lib64/python3.8/site-packages/yaml/nodes.py
/tmp/i/usr/local/lib64/python3.8/site-packages/yaml/parser.py
/tmp/i/usr/local/lib64/python3.8/site-packages/yaml/reader.py
/tmp/i/usr/local/lib64/python3.8/site-packages/yaml/representer.py
/tmp/i/usr/local/lib64/python3.8/site-packages/yaml/resolver.py
/tmp/i/usr/local/lib64/python3.8/site-packages/yaml/scanner.py
/tmp/i/usr/local/lib64/python3.8/site-packages/yaml/serializer.py
/tmp/i/usr/local/lib64/python3.8/site-packages/yaml/tokens.py
/tmp/i/usr/local/lib64/python3.8/site-packages/PyYAML-5.3.1.dist-info/RECORD
/tmp/i/usr/local/lib64/python3.8/site-packages/PyYAML-5.3.1.dist-info/INSTALLER
/tmp/i/usr/local/lib64/python3.8/site-packages/PyYAML-5.3.1.dist-info/LICENSE
/tmp/i/usr/local/lib64/python3.8/site-packages/PyYAML-5.3.1.dist-info/METADATA
/tmp/i/usr/local/lib64/python3.8/site-packages/PyYAML-5.3.1.dist-info/WHEEL
/tmp/i/usr/local/lib64/python3.8/site-packages/PyYAML-5.3.1.dist-info/top_level.txt
ssato@x1-carbon-gen6%
```

**Comment by adrienverge** [comment]
Very cool PR, thanks @ssato :+1: 

Could you just squash commits 1 and 3, since they go together?

**Comment by ssato** [comment]
Thanks for your quick response!

> Could you just squash commits 1 and 3, since they go together?

I tried that. Could you please check the latest force-pushed one?

**Comment by adrienverge** [comment]
Unfortunately you just squashed the 2nd commit (7d9d721 -- Add some metadata will provides extra info in its PyPI page) too.

Can you restore it? Otherwise I can take some time later to do it.

**Comment by ssato** [comment]
> Unfortunately you just squashed the 2nd commit ([7d9d721](https://github.com/adrienverge/yamllint/commit/7d9d721aa6a0e2f3d220b6475ba007c678733bc4) -- Add some metadata will provides extra info in its PyPI page) too.
> 
> Can you restore it? Otherwise I can take some time later to do it.

Oh, I misunderstood you want  me to squash all of them, sorry. Wait for a minute, please, and I'll retry to squash the commits excluding the commit 7d9d721 you mentioned if it's OK.

**Comment by ssbarnea** [comment]
I totally support this move. Setup,py should not be longer than 4 lines of code and that is needed only to keep editable installs working. All the rest must go into setup.cfg and pyproject.toml

Versioning works so nicely with setuptools-scm.

**Comment by adrienverge** [comment]
> > Unfortunately you just squashed the 2nd commit ([7d9d721](https://github.com/adrienverge/yamllint/commit/7d9d721aa6a0e2f3d220b6475ba007c678733bc4) -- Add some metadata will provides extra info in its PyPI page) too.
> > Can you restore it? Otherwise I can take some time later to do it.
> 
> Oh, I misunderstood you want me to squash all of them, sorry. Wait for a minute, please, and I'll retry to squash the commits excluding the commit [7d9d721](https://github.com/adrienverge/yamllint/commit/7d9d721aa6a0e2f3d220b6475ba007c678733bc4) you mentioned if it's OK.

@ssato but https://github.com/adrienverge/yamllint/commit/7d9d721aa6a0e2f3d220b6475ba007c678733bc4 is a good change, my thought was to include it (as a second commit). It's just commits 1 and 3 that were parts of the same change, and that needed to be squashed.

**Comment by ssato** [comment]
> > > Unfortunately you just squashed the 2nd commit ([7d9d721](https://github.com/adrienverge/yamllint/commit> @ssato but [7d9d721](https://github.com/adrienverge/yamllint/commit/7d9d721aa6a0e2f3d220b6475ba007c678733bc4) is a good change, my thought was to include it (as a second commit). It's just commits 1 and 3 that were parts of the same change, and that needed to be squashed.

OK, I understand and push that as another commit again. Could you please check that?

**Review by adrienverge — APPROVED** [review]
Thank you @ssato!

**Pull request merged**
