### PR TITLE
Travis CI: Add Python 3.7, 3.8a, Drop Python 3.3

### PR DESCRIPTION
**Pull request by cclauss**
* Adds Python 3.7.1 and a current nightly build of Python 3.8 alpha.
* Python 3.3 reached its end of life in 2017 https://devguide.python.org/#branchstatus

### CODE REVIEW

**Comment by adrienverge** [comment]
Hi @cclauss,

I already created the [test/python3.7](https://github.com/adrienverge/yamllint/tree/test/python3.7) branch yesterday!

I prefer avoiding the "matrix" trick. The simple "3.7" option should be supported very soon: https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-438518560

**Comment by cclauss** [comment]
Why does Python 3.8 fail?

**Comment by cclauss** [comment]
xenial is available != xenial is default

https://blog.travis-ci.com/2018-11-08-xenial-release

Even though xenial is officially available, you still need to specify __dist: xenial__ until xenial is the default.

**Comment by cclauss** [comment]
So... inf we want to support Python 2.6 and 3.7 then we can not avoid the "maxtix trick" because 2.6 will not run on xenial and Python 3.7 will not run on trusty.  Do we drop Python 2.6?  Its end of life was _five years ago_.

**Comment by cclauss** [comment]
Also the timeout on the Python 3.5 build is a continuing sign of the fragility of Travis' xenial builds.  https://travis-ci.org/adrienverge/yamllint/builds/455400506  To me, the "matrix trick" does not look so bad.

**Comment by hugovk** [comment]
Python 2.6 can now be dropped. It was kept because yamllint was a dependency of Ansible, but Ansible dropped 2.6 last month, so yamllint should also drop it.

See https://github.com/adrienverge/yamllint/pull/149.

**Comment by adrienverge** [comment]
Thanks @cclauss, the PR looks shorter and nicer now, and it's better without `sudo`.

Can you rebase on `master` and squash everything into a single commit?
Also, I'd rather avoid the `allow_failures` trick and run `flake8` only if Python != 3.8. The error seems temporary and will probably be fixed upstream soon. That way, unit tests will still be run and reported on 3.8.

**Comment by cclauss** [comment]
How about if we run flake8 only if Python == *.7 so that we run it once on Python 2 and once on Python 3.  The various versions of Python 3 share a common Abstract Syntax Tree so running the same tests over the same AST is redundant.  The Python 3.7 AST is a good choice because it is a bit stricter than the others because it adds new keywords __async__ and __await__ which were not reserved words in Python <= 3.6.

**Comment by adrienverge** [comment]
It looks like a good idea! But linting and tests are run during packaging for some Linux distributions. Those have various Python versions. If `flake8` starts failing for a specific version, I prefer knowing it via Travis.

**Comment by adrienverge** [comment]
@cclauss I just saw that you've updated the pull request 6 days ago (I don't get notifications if you don't push anything).

The PR looks perfect, but now it conflicts...
Can you update (and post a message)?
Thanks!

**Comment by adrienverge** [comment]
You reverted the `if [[ $TRAVIS_PYTHON_VERSION != nightly ]]; then flake8 .; fi` change. So CI tests don't pass anymore.

**Comment by cclauss** [comment]
__if [[ $TRAVIS_PYTHON_VERSION != nightly ]]; then flake8 .; fi__ is now back in place.

**Comment by hugovk** [comment]
I see "This branch has no conflicts with the base branch".

image

**Comment by adrienverge** [comment]
Can you please rebase on **latest** `master`, squash all your commits and push force?

capture d ecran de 2018-12-10 16-51-55

**Comment by cclauss** [comment]
Closed in favor of #153.

**Pull request closed without merging**
