### PR TITLE
Feature: Quoted strings value rule

### PR DESCRIPTION
**Pull request by mgmgwi**
* taken from https://github.com/adrienverge/yamllint/pull/110 (submitted by @jurajseffer)
* small fix for generic strings
* fixes for comments from @adrienverge

### CODE REVIEW

**Comment by mgmgwi** [comment]
I don't know how to fix the `The command "pip install pyyaml flake8 flake8-import-order coveralls" failed and exited with 1 during` problem from the python 2.6 build.

**Comment by mgmgwi** [comment]
@adrienverge: Any feedback would be very much appreciated.

**Comment by adrienverge** [comment]
Hi @mgmgwi,

Thanks for all that good work.

I pushed a commit to your branch, with changes I wanted to see:
- list this rule in `default.yaml`,
- clarify the doc a bit,
- add a few more test cases.

In these new test cases, the rule currently fails on multi-line strings.
I think it's important that *explicit* multi-line strings (with `|` or `>`) pass the test, without a need to add quotes:
```yaml
multiline string 1: |
  line 1
  line 2
multiline string 2: >
  word 1
  word 2
```

What do you think? Maybe we could use other properties of `ScalarToken` (`plain`, `style`, `start_mark`, `end_mark`) to detect multiline `>` and `|` cases?

@jurajseffer any thoughts?

**Comment by mgmgwi** [comment]
@adrienverge Thanks for your feedback. 

> I think it's important that explicit multi-line strings (with | or >) pass the test, without a need to add quotes.

I agree with you on that.


> What do you think? Maybe we could use other properties of `ScalarToken` (`plain`, `style`, `start_mark`, `end_mark`) to detect multiline `>` and `|` cases?

I added a patch which ignores multi-line strings. Do you think that's ok?

**Comment by adrienverge** [comment]
> I don't know how to fix the `The command "pip install pyyaml flake8 flake8-import-order coveralls" failed and exited with 1 during` problem from the python 2.6 build.

Sorry about that, `coveralls` no longer supports Python 2.6 so builds started to fail recently. This is fixed on `master` now.

> Do you think that's ok?

It looks great! I just added an extra commit with another type of multi-line string (and it works as expected).
If this OK for you, can you squash all commits, rebase on `master` and push again? Tests should pass then.

**Comment by mgmgwi** [comment]
> If this OK for you, can you squash all commits, rebase on master and push again? Tests should pass then.

@adrienverge: Thanks again for your feedback. Checks are looking good now.

**Comment by adrienverge** [comment]
Thank you and @jurajseffer for contributing!

I'll make a new release that includes this new rule.

**Pull request merged**
