### PR TITLE
CI: Add support for Python 3.11

### PR DESCRIPTION
**Pull request by michael-k**

### CODE REVIEW

**Comment by adrienverge** [comment]
Thanks for contributing!

Could you rename the commit to `CI: Add support for Python 3.11` for consistency with other commits?

**Comment by michael-k** [comment]
I did rename the commit as requested ~1.5 hours ago.  I don't know why the PR UI doesn't pick that up.  The [branch](https://github.com/michael-k/yamllint/tree/python3.11) shows the updated commit.

**Comment by adrienverge** [comment]
Strange! Maybe you could try `git commit --amend --no-edit && git push -f` to force GitHub to update?

**Comment by michael-k** [comment]
I did another `git push --force-with-lease` after amending the commit.  So far the PR has not picked that up.  https://www.githubstatus.com/ is green (but reported issues earlier today)

**Comment by michael-k** [comment]
But after closing the PR GitHub says that the branch was force-pushed and doesn't let me open the PR again …
Should I open a new one or do you want to pull/cherry-pick the commit directly?

**Comment by adrienverge** [comment]
I tried `push -f` to your repo, it didn't update the commit on the UI.

> you can merge my branch directly.

I'll do that!

Thanks for contributing!

**Comment by adrienverge** [comment]
PS: After pushing `master`, GitHub automatically marked the PR as merged, so we're good even on the UI :+1:

**Pull request merged**
