### PR TITLE
pre-commit is now served over https!

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by asottile** [comment]
failure for nightly seems to be https://github.com/yaml/pyyaml/issues/126

**Comment by adrienverge** [comment]
> failure for nightly seems to be yaml/pyyaml#126

Yes, it happens on `master` too, sorry about that!

**Comment by hugovk** [comment]
Good news: PyYAML 4.1 has been released which now installs successfully on Python 3.7.

https://github.com/yaml/pyyaml/issues/126#issuecomment-400679908

**Comment by adrienverge** [comment]
@hugovk that's great! I confirm that tests are passing again on Python 3.7 :+1:

**Pull request merged**
